### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [janaSunrise/janaSunrise#2]
[Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)

**Comment by Vyvy-vi** [comment]
@VasudevJaiswal This is NOT the way to promote your organisation.

Spamming invites in repositories of people is NOT a good way to "promote" your community. It's the fastest way for people to blacklist you and your org.
Moreover, I don't think it's in good spirit that you joined an org's discord, got the github details of its members, and then spammed them links to your own community...

**Comment by VasudevJaiswal** [comment]
Sorry for that

**Comment by VasudevJaiswal** [comment]
> @VasudevJaiswal This is NOT the way to promote your organisation.
> 
> Spamming invites in repositories of people is NOT a good way to "promote" your community. It's the fastest way for people to blacklist you and your org.
> Moreover, I don't think it's in good spirit that you joined an org's discord, got the github details of its members, and then spammed them links to your own community...

What's the method

**Comment by Vyvy-vi** [comment]
I would recommend _organic growth_.

Make a good community project or event or content(blog/video/podcast), try sharing the project's repo with people in other communities, who might want to collaborate on that project. Some people might collaborate on the project.

Many people might join your org, if they see that it creates value.
Spamming your org's invite is actually a red-flag and makes people more hesitant to join the org...

**Comment by janaSunrise** [comment]
I second this. This is more of a spammy thing, rather than a good spirit. Randomly asking people to join, spamming their repos, is not right. I hope you change this attitude towards people, and especially Open-source and the platforms.
